//
//  PreviewServer.swift
//  Photo Club Hub HTML
//
//  Created by Claude Code under supervision of Peter van den Hamer on 12/08/2026.
//

import Foundation  // for URL, FileManager
import FlyingFox   // for HTTPServer
import FlyingSocks // for sockaddr_in.inet(ip4:port:), SocketError

// MARK: - Preview Server

/// Serves the generated site over HTTP so it can be viewed in a browser (#249, replacing #247's
/// hand-written server generated by Claude Code).
///
/// Providing a server is important here because the generated pages link root-relative (`/en/clubs/`).
/// That won't work because `file://` resolves against the filesystem root,
/// and directory URLs like `/en/clubs/` need index resolution that `file://` doesn't provide.
///
/// The HTTP protocol implementation uses [FlyingFox](https://github.com/swhitty/FlyingFox).
/// This actor owns only the lifecycle and the port policy.
/// Path resolution stays in ``PreviewSiteHandler``, because
/// FlyingFox's own directory handler doesn't resolve a directory URL to its `index.html`.
///
/// Binds loopback by default, and every interface only when the user asks for it via
/// `PreferencesStructHTML.allowRemotePreview`.
///
/// Reaching the preview from a phone or tablet is the only way to check the responsive layout of the
/// generated pages, and there is nothing in them to keep private: they are generated *for* public hosting,
/// out of JSON that is already public on GitHub, where the sibling Photo Club Hub app reads it. But it stays
/// off by default because binding every interface makes macOS ask the user to allow incoming connections —
/// a prompt nobody who only previews on this Mac should ever have to see — and because an App Store build
/// that listens on every interface out of the box invites an avoidable question.
///
/// When it *is* on, FlyingFox's `HTTPServer(port:)` binds the IPv6 wildcard, and `net.inet6.ip6.v6only` is 0
/// on macOS, so IPv4 clients reach it too. Either way ``PreviewSiteHandler`` keeps the server to files under
/// `directory`.
///
/// Otherwise the server runs until the app exits, at which point the OS closes the listening socket and every
/// open connection; there is no command that stops it sooner. The only thing that stops it earlier is
/// a change to that setting: #247's server had no `stop()` at all, but a preference the user can flip has to
/// take effect when it is flipped, which is what ``applyRemoteAccess(_:directory:)`` is for.
actor PreviewServer {

    static let shared = PreviewServer()

    // Stored solely to keep the server and its run loop alive: nothing reads them, but dropping the Task
    // would tear down the listener.
    private var server: HTTPServer?
    private var runTask: Task<Void, Never>?

    /// Holds why the current bind attempt's run loop failed, if it did. See ``bind(port:directory:)``.
    private var runFailure: (any Error)?

    /// The port currently being served, or nil when the server isn't running.
    private(set) var boundPort: UInt16?

    /// The `allowRemoteAccess` the running listener was bound with, or nil when nothing is running.
    ///
    /// A Bool rather than a list of interfaces because only two bind addresses are ever used, and
    /// ``bind(port:directory:allowRemoteAccess:)`` picks between them: `true` is the IPv6 wildcard, which
    /// accepts connections arriving on any interface, and `false` is `127.0.0.1` alone. Recording which one
    /// is live lets ``start(preferredPort:directory:allowRemoteAccess:)`` tell "already serving what you are
    /// asking for" from "serving, but not reachable the way you are now asking for" — only the second needs
    /// a rebind.
    private var boundRemoteAccess: Bool?

    /// How many consecutive ports to try before giving up when the preferred one is taken.
    private static let maxPortAttempts = 10

    /// How long to wait for the listener to come up before treating the attempt as failed.
    private static let listenTimeout: TimeInterval = 5 // seconds

    /// Starts serving `directory`, returning the port it ended up on.
    ///
    /// Starting is idempotent *for a given `allowRemoteAccess`*: calling this again while the server runs on the
    /// address asked for returns the port already bound, without rebinding. Asking for the other address stops
    /// the listener and binds again, because the alternative is a preference that appears to do nothing
    /// until the next launch. When `preferredPort` is occupied — by anything else on this Mac already listening
    /// there — the next free port is used instead. That costs nothing a preview cares about: only the site's
    /// SEO metadata (`rel="canonical"`, `og:url`, `sitemap.xml`) carries the port baked in at generation time,
    /// while every navigational link is root-relative.
    ///
    /// - Parameters:
    ///   - preferredPort: The port to try first, normally ``SiteOutput/defaultPreviewPort``.
    ///   - directory: The directory to serve, normally ``SiteOutput/buildDirectory``.
    ///   - allowRemoteAccess: Whether to listen on every interface rather than loopback only. A change of mind
    ///     here is what triggers a rebind; the port may come back different if something took the old one in
    ///     between, which is why callers use the returned port rather than the one they asked for.
    /// - Returns: The port actually bound, which may differ from `preferredPort`.
    func start(preferredPort: UInt16,
               directory: URL,
               allowRemoteAccess: Bool) async throws -> UInt16 {

        // related to "Allow previewing on other devices too" toggle flipping while we are alredy underway
        if let boundPort, boundRemoteAccess == allowRemoteAccess { return boundPort }
        if boundPort != nil { await stop() } // serving, but bound to the other address, so rebind below

        guard FileManager.default.fileExists(atPath: directory.path(percentEncoded: false)) else {
            throw PreviewServerError.siteNotGenerated
        }

        var candidate = preferredPort
        for _ in 0..<Self.maxPortAttempts {
            do {
                let port = try await bind(port: candidate,
                                          directory: directory,
                                          allowRemoteAccess: allowRemoteAccess)
                boundPort = port
                boundRemoteAccess = allowRemoteAccess
                return port
            } catch PreviewServerError.portInUse {
                // UInt16 overflow would need 20 attempts from 65516 upwards; stop rather than wrap to 0.
                guard candidate < UInt16.max else { break }
                candidate += 1
            }
            // Any other error — e.g., a sandbox denial — is not something a different port would fix,
            // so it propagates instead of burning through maxPortAttempts attempts and reporting "no free port".
        }
        throw PreviewServerError.noFreePort(preferred: preferredPort, tried: Self.maxPortAttempts)
    }

    /// Rebinds a *running* server to the address the setting now asks for, keeping the port it already has.
    ///
    /// Without this, the toggle would only take effect at the next preview, which reads as a setting that
    /// quietly ignores you: the obvious way to check it is to reload the page that is already open, and that
    /// keeps working. Doing nothing when the server is not running is not a special case — there is no listener
    /// to move, and ``start(preferredPort:directory:allowRemoteAccess:)`` will read the setting when it binds.
    ///
    /// - Throws: Whatever a rebind throws. The old listener is closed before the new one is bound, so a failure
    ///   here leaves no server running; the next preview starts one from scratch.
    func applyRemoteAccess(_ allowRemoteAccess: Bool, directory: URL) async throws {
        guard let boundPort, boundRemoteAccess != allowRemoteAccess else { return }
        _ = try await start(preferredPort: boundPort, directory: directory, allowRemoteAccess: allowRemoteAccess)
    }

    /// Closes the listener and forgets what was bound, so the next
    /// ``start(preferredPort:directory:allowRemoteAccess:)`` starts from scratch.
    ///
    /// The await on ``runTask`` is the part that is easy to leave out and expensive to leave out. FlyingFox's
    /// `stop()` closes the listening socket and returns, but `run()` is still unwinding on our own task, and
    /// its `SocketPool` closes the kqueue descriptor on the way out. Binding the replacement server before that
    /// finishes lets the new pool open a descriptor the old one is about to close, and the rebind dies with
    /// `kevent: Bad file descriptor` — reliably, on the first attempt, while a later retry succeeds.
    ///
    /// `SO_REUSEADDR` is set on the listener by FlyingSocks, so reclaiming the same port straight afterwards
    /// does not trip over `TIME_WAIT`. Clearing ``runFailure`` matters too: the cancelled `run()` records one
    /// on its way out, and a stale error would otherwise be read as the *next* bind's verdict.
    private func stop() async {
        runTask?.cancel() // `run()` stops its accept loop when the task awaiting it is cancelled
        await server?.stop()
        await runTask?.value // only now is the pool's kqueue actually closed
        server = nil
        runTask = nil
        runFailure = nil
        boundPort = nil
        boundRemoteAccess = nil
    }

    /// Binds one specific port, returning once the listener is up.
    ///
    /// `run()` blocks for the server's whole lifetime on success but throws promptly on a failed bind, so
    /// the two outcomes have to be watched at once. They cannot simply be raced in a task group: awaiting
    /// an unstructured `Task`'s `value` ignores the *caller's* cancellation, so the losing child would park
    /// on a `run()` that never returns and the group would never finish. Hence the run task reports a
    /// failure through ``runFailure`` and this polls both signals — a busy port is detected in milliseconds
    /// rather than after a five second wait per attempt.
    private func bind(port: UInt16, directory: URL, allowRemoteAccess: Bool) async throws -> UInt16 {
        let handler = PreviewSiteHandler(root: directory)
        let server: HTTPServer
        if allowRemoteAccess {
            // FlyingFox's convenience initializer is exactly the wildcard bind, so it is the right one here.
            server = HTTPServer(port: port, handler: handler)
        } else {
            // Anything else would expose the listener: `HTTPServer(port:)` binds the wildcard, which accepts
            // connections arriving on any interface. A LAN client cannot reach 127.0.0.1, which is the point.
            server = HTTPServer(address: try sockaddr_in.inet(ip4: "127.0.0.1", port: port), handler: handler)
        }

        runFailure = nil
        let task = Task { [weak self] in
            do {
                try await server.run()
            } catch {
                await self?.recordRunFailure(error)
            }
        }

        let deadline = ContinuousClock.now.advanced(by: .seconds(Self.listenTimeout))
        while ContinuousClock.now < deadline {
            if await server.isListening {
                self.server = server
                self.runTask = task
                return port // an explicit port was requested, so the listener is on exactly that port
            }
            if let failure = runFailure {
                task.cancel()
                throw Self.mapped(failure)
            }
            try await Task.sleep(for: .milliseconds(5))
        }

        task.cancel()
        throw PreviewServerError.listenerFailed("the listener did not come up within " +
                                                "\(Int(Self.listenTimeout)) seconds")
    }

    /// Records why the server's own run loop gave up, so ``bind(port:directory:)`` can tell a refused bind
    /// from a listener that is merely slow to come up.
    private func recordRunFailure(_ error: any Error) {
        runFailure = error
    }

    private static func mapped(_ error: any Error) -> PreviewServerError {
        // EADDRINUSE is the retryable one. EACCES is not: on a port above 1024 it means the sandbox
        // refused to let the app listen at all, and trying 19 more ports would only obscure that.
        if case SocketError.failed(_, let errno, _) = error, errno == EADDRINUSE {
            return .portInUse
        }
        return .listenerFailed(error.localizedDescription)
    }

}

// MARK: - Error messages

enum PreviewServerError: LocalizedError {
    case siteNotGenerated
    case portInUse
    case noFreePort(preferred: UInt16, tried: Int)
    case listenerFailed(String)

    var errorDescription: String? {
        switch self {
        case .siteNotGenerated:
            String(localized: "There is no generated website yet. Use Actions → Generate website first.",
                   table: "PhotoClubHubHTML.SwiftUI",
                   comment: "Error shown when previewing before the website has been generated")
        case .portInUse:
            String(localized: "That port is already in use.",
                   table: "PhotoClubHubHTML.SwiftUI",
                   comment: "Error shown when the preview server cannot claim a port")
        case .noFreePort(let preferred, let tried):
            String(localized: "No free port found in the \(tried) ports starting at \(Int(preferred)).",
                   table: "PhotoClubHubHTML.SwiftUI",
                   comment: "Error shown when every candidate port for the preview server is occupied")
        case .listenerFailed(let reason):
            String(localized: "The preview server could not start: \(reason)",
                   table: "PhotoClubHubHTML.SwiftUI",
                   comment: "Error shown when the preview server fails for a reason other than a busy port")
        }
    }
}
